version: "2.1"

networks:
  network-dog:
    external: true

services:
  backend:
    container_name: dog_api_container
    restart: always
    build: .
    environment:
      - APP_ENV=development
      - APP_PORT=9000
    volumes:
      - ./src:/var/www/backend/src
      - ./test:/var/www/backend/test
      - ./secrets:/var/www/backend/secrets
    working_dir: /var/www/backend
    ports:
      - "9001:9000"
    links:
      - maria_db
    depends_on:
      - maria_db
    networks:
      - network-dog

  maria_db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dog_api_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3305:3306"
    volumes: 
        - ./init:/docker-entrypoint-initdb.d
    networks:
      - network-dog